version: '3.9'

services:
  postgres_big_test_db:
    image: postgres
    container_name: postgres_big_test_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres_big_test_db_user
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: big_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
